name: Events Demo 1
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "dev-*-test"
  pull_request:
    types:
      - opened
      - assigned
      - closed
    branches:
      - "main"
      - "dev-*-prod"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output Event data
        run: echo "${{ toJSON(github) }}"
      - name: GET CODE
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build project
        run: npm run build
      - name: Deploy Project
        run: echo "deploying .........."
